services:
  - type: web
    name: first-ml-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn first_ml_project.predict_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_TOKEN
        value: demo-token
